name: Publish to NPM

on:
  release:
    types: [ published ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Node Setup
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          registry-url: https://registry.npmjs.org/
          scope: '@yudiel'

      - name: Install Dependencies
        run: yarn

      - name: Build
        run: yarn build

      - name: Publish Pre-release
        if: ${{ github.event.release.prerelease == true }}
        run: npm publish --tag beta --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish Release
        if: ${{ github.event.release.prerelease == false }}
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}